### ISSUE TITLE
在运行程序的时候出现了这样的问题请问怎么解决？

### ISSUE THREAD

**Issue by 1614255035** [liun-online/CoGSL#1]
![image](https://user-images.githubusercontent.com/114007200/191297538-e142a3a7-fd68-4d5a-b5b9-090957e2cdef.png)
Traceback (most recent call last):
  File "F:/CoGSL-main/code/main.py", line 6, in <module>
    from params import set_params
  File "F:\CoGSL-main\code\params.py", line 5, in <module>
    dataset = argv[1]
IndexError: list index out of range
本人新手一枚，希望各位老师不吝赐教。

**Comment by liun-online** [comment]
请问你的命令行怎么写的

**Comment by 1614255035** [comment]
老师您好，我命令行没写东西。我是把代码和数据下载下来解压了，然后把需要的模块都下载下来，直接运行的。
&nbsp;


宝贝儿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nian ***@***.***&gt;; 
发送时间: 2022年9月20日(星期二) 晚上11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liun-online/CoGSL] 在运行程序的时候出现了这样的问题请问怎么解决？ (Issue #1)





 
请问你的命令行怎么写的

**Comment by liun-online** [comment]
看一下这个代码的github主页，在数据集下面有给出命令行怎么写
![捕获](https://user-images.githubusercontent.com/52119585/191300483-2c01bf7d-5109-4ebf-8395-ee96cdb35df0.PNG)
每个命令行里的数据集根据你的需要换成不同的名称

**Comment by liun-online** [comment]
需要linux环境下跑实验

**Comment by 1614255035** [comment]
好的麻烦您了，我是一个研一新生，学长让我帮他跑一下程序。刚接触这方面还没入门，不知道该怎么跑实验，给您添麻烦了。您能简单指教一下我该怎么才能跑起实验来吗？如果不方便的话也没关系，我自己学习一下。再次感谢您。
&nbsp;


宝贝儿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nian ***@***.***&gt;; 
发送时间: 2022年9月20日(星期二) 晚上11:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liun-online/CoGSL] 在运行程序的时候出现了这样的问题请问怎么解决？ (Issue #1)





 
需要linux环境下跑实验

**Comment by liun-online** [comment]
抱歉，在这里我只能回答和代码细节或者论文相关的问题，其他问题实在不能帮到你

**Comment by 1614255035** [comment]
好的，请问数据集中的ori_view1_indice指的是什么？View Estimator中的MLP是如何被训练的，需要迭代吗，需要反向传播吗？
&nbsp;


宝贝儿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nian ***@***.***&gt;; 
发送时间: 2022年9月21日(星期三) 凌晨0:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liun-online/CoGSL] 在运行程序的时候出现了这样的问题请问怎么解决？ (Issue #1)





 
抱歉，在这里我只能回答和代码细节或者论文相关的问题，其他问题实在不能帮到你

**Comment by liun-online** [comment]
ori_view1_indice指的是view1学结构的范围，我只学在该范围内的连边情况。其他问题，我推荐你可以先了解一下pytorch，以及如何用pytorch搭建模型，还有整个训练流程是怎样的。可以先从简单的pytorch搭建的模型入手。

**Comment by 1614255035** [comment]
好的，感谢您。我在github上新发了一个问题是我同门师哥想要请教您的，希望在您有时间的时候可以赐教一下。


---原始邮件---
发件人: &quot;Nian ***@***.***&gt;
发送时间: 2022年9月21日(周三) 上午10:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liun-online/CoGSL] 在运行程序的时候出现了这样的问题请问怎么解决？ (Issue #1)




 
ori_view1_indice指的是view1学结构的范围，我只学在该范围内的连边情况。其他问题，我推荐你可以先了解一下pytorch，以及如何用pytorch搭建模型，还有整个训练流程是怎样的。可以先从简单的pytorch搭建的模型入手。
 
&mdash;
