### ISSUE TITLE
有一些论文中的问题想要请教您

### ISSUE THREAD

**Issue by 1614255035** [liun-online/CoGSL#2]
论文中提出并使用了basic views，请问为什么还需要view Estimator,它起到了什么重要的作用。另外请问节点嵌入Z的质量对学习出最优的View Estimator之间是否存在关系，即高质量的节点嵌入Z是不是学习出更优秀的View Estimator的必要条件。

**Comment by liun-online** [comment]
因为这篇文章是图结构学习，如果没有view estimator就没法学习结构，也就不叫图结构学习了，就只剩下单纯如何去融合两个basic view了。输入view estimator的gcn编码后的Z不是最终需要用于下游任务的节点嵌入，其学习过程是和后续模型联合在一起的，并不是先学好Z再经过view estimator的。因此他们之间没有谁先学好谁后学好的关系，两者相辅相成。
