### ISSUE TITLE
关于标签信息

### ISSUE THREAD

**Issue by chenx-hi** [liun-online/CoGSL#3]
您好，阅读您的文章，感觉受益匪浅。

想请教一下论文中的标签信息YL，H(YL)是整个图中所有节点的熵，还是节点分类任务中除给定标签节点的剩余节点的熵。

**Comment by liun-online** [comment]
您好，感谢关注。

这里的H(YL)就是有标签节点的熵。我想你的疑问可能是给定了的标签是没有不确定度的，因此其对应的H(YL)为0。其实论文推导中，YL被看做是一个变量，而不是一个确定的值。推导的时候，只是去考量不同视图和标签的关系，而到具体实现时再代入标签的真实值。H(YL)选择有标签节点，是因为对于无标签的节点即使我们推导出了他们标签和视图间的关系，也很难去实际量化这种关系。你可以参考DEEP VARIATIONAL INFORMATION BOTTLENECK中对label的运用

**Comment by chenx-hi** [comment]
似乎理解了，谢谢您的讲解！
